[package]
name = "encoding"
version = "0.2.0"
authors = ["sammyne <xiangminli@alumni.sjtu.edu.cn>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
#serde = "1.0.104"
lazy_static = "1.4.0"
thiserror   = "1.0.16"

[dev-dependencies]
criterion = "0.3"

[[bench]]
name = "base32"
harness = false

[[bench]]
name = "hex"
harness = false
