[package]
name = "pem"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
base64.workspace = true
builtin.workspace = true
thiserror.workspace = true

[dev-dependencies]
lazy_static.workspace = true
